# Generated by Django 5.2.17 on 2026-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('eligibility', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
