# Generated by Django 5.2.17 on 2026-09-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0004_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placement_student.recruiter'),
            preserve_default=False,
        ),
    ]
