# Generated by Django 5.2.17 on 2026-09-26 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0007_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
