# Generated by Django 5.2.17 on 2026-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0008_recruiter_company_address_recruiter_company_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eligibility',
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_courses',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_departments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='graduation_year',
            field=models.IntegerField(default=2027),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(default=2027),
        ),
    ]
