# Generated by Django 5.2.17 on 2026-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0010_resume_uploaded_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
