# Generated by Django 5.2.17 on 2026-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0011_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
