# Generated by Django 5.2.17 on 2026-09-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0013_job_application_deadline_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Job', 'New Job'), ('Status Update', 'Status Update'), ('Deadline', 'Deadline'), ('Interview', 'Interview'), ('General', 'General')], default='General', max_length=30),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('venue', models.CharField(blank=True, default='', max_length=300)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='placement_student.application')),
            ],
        ),
    ]
