# Generated by Django 5.2.17 on 2026-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0017_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_photos/'),
        ),
    ]
