# Generated by Django 5.2.17 on 2026-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_student', '0018_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='available_to_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='comfortable_with_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='consent_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_active_backlogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_work_shifts',
            field=models.BooleanField(default=False),
        ),
    ]
